### ISSUE TITLE
Please add docker-compose.yml file

### ISSUE THREAD

**Issue by ben-kenney** [TypingMind/plugins-server#44]
**Let's Talk About Your Feature Idea**

We're always looking for ways to improve TypingMind Proxy! Let's discuss how your feature could address current limitations and enhance the plugin development experience.

**1. What problem does this solve?**

Makes it easier for user to start the docker service.

**2. Describe your proposed solution.**

Include the following `docker-compose.yml` file in the repo:
```
services:
  typingmind-plugins-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
```

This way user just need to run: `docker compose up -d`
